name: yarn upgrade package

on:
  schedule:
    - cron: 0 1 * * 5
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 15 ]

    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true

    - name: cache npm
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: install yarn
      run: npm install -g npm@latest yarn@latest synp@latest

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: cache yarn 1
      uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: clean install
      run: |
        rm -rf node_modules
        rm -fv package-lock.json yarn.lock
        git add "*"
        yarn
        yarn upgrade --latest
        # synp --source-file yarn.lock
        rm -rf node_modules
        git add package-lock.json || echo ok > /dev/null
        git add yarn.lock || echo ok > /dev/null
        git add "*"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "[chore] packages update"
        commit-message: "packages update"
        branch: chore/update-package
        signoff: true
        delete-branch: true
        branch-suffix: timestamp
        assignees: ${{ github.actor }}
        reviewers: ${{ github.actor }}
        draft: false
